[build-system]   
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"    
     
[project]        
name = "faker-pk"
version = "0.1.9"                
description = "Fake data generator for Pakistani names, CNICs, personal info, address info, job titles, IBAN, Bank names, cities, provinces, castes, sect, network providers, job aware salaries and companies info."   
readme = "README.md"   
authors = [
    { name = "Muhammad Khubaib Ahmad", email = "khubaib.ahmad@inference-lab.org" },
    { name = "INFERENCE Lab", email = "contact@inference-lab.org" }
]

maintainers = [
    { name = "INFERENCE Lab", email = "contact@inference-lab.org" }
]
license = { text = "MIT" }   
requires-python = ">=3.8"
dependencies = ["faker"]
keywords = ["faker", "pakistan", "data", "mock", "testing"]
classifiers = [
    "Programming Language :: Python :: 3",  
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]    
[tool.setuptools.package-data]
faker_pk = ["*.db"]
[project.urls]   
"Homepage" = "https://github.com/Inference-LAB/faker-pk"   